a = []
print("THe user need to enter the seven fruits")
f1 = input("Enter Fruit name ; ")
a.append(f1)
f2 = input("Enter Fruit name ; ")
a.append(f2)
f3 = input("Enter Fruit name ; ")
a.append(f3)
f4 = input("Enter Fruit name ; ")
a.append(f4)
f5 = input("Enter Fruit name ; ")
a.append(f5)
f6 = input("Enter Fruit name ; ")
a.append(f6)
f7 = input("Enter Fruit name ; ")
a.append(f7)
print(a)