a = []
print("THe user need to enter the seven marks")
f1 = int(input("Enter marks of the student: "))
a.append(f1)
f2 = int(input("Enter marks of the student: "))
a.append(f2)
f3 = int(input("Enter marks of the student: "))
a.append(f3)
f4 = int(input("Enter marks of the student: "))
a.append(f4)
f5 = int(input("Enter marks of the student: "))
a.append(f5)
f6 = int(input("Enter marks of the student: "))
a.append(f6)
f7 = int(input("Enter marks of the student: "))
a.append(f7)
a.sort()
print(a)