d = {}
name =input("Enter the friend name :")
lang =input("Enter the friend language  :")
d.update({name : lang})
name =input("Enter the friend name :")
lang =input("Enter the friend language  :")
d.update({name : lang})
name =input("Enter the friend name :")
lang =input("Enter the friend language  :")
d.update({name : lang})
name =input("Enter the friend name :")
lang =input("Enter the friend language  :")
d.update({name : lang})
print(d)